In [ ]:
'''
🚀 PROJETO 9 — 
🧠 Tema do projeto
Análise de comportamento de clientes (Customer Analytics)


🎯 Objetivo

Você vai responder:

Quem são os melhores clientes?
Onde está o dinheiro?
Quem está sendo subaproveitado?
🧱 O que você VAI construir

Um mini pipeline com:

dados → transformação → métricas → segmentação → insights
📦 Dataset

👉 Use o mesmo (Superstore / Kaggle)

Isso é proposital:

menos esforço técnico → mais foco analítico
🧭 ETAPA 1 — Base de dados

Crie tabelas claras:

df_orders
df_customers

👉 Depois:

df_final (joinado)
🧭 ETAPA 2 — Criação de métricas

Você NÃO vai só agregar.

Você vai criar métricas por cliente.

Perguntas que guiam:

quanto cada cliente gasta?
quantas compras faz?
qual ticket médio?

⚠️ Você deve chegar em algo tipo:
Customer Name | Total_Revenue | Total_Orders | Avg_Ticket

🧭 ETAPA 3 — Feature Engineering (o diferencial)

Agora você começa a pensar como analista de verdade.

Crie pelo menos 2 dessas:

- ticket médio
- frequência de compra
- receita total por cliente
- ranking de clientes

🧭 ETAPA 4 — Segmentação 
Você vai dividir clientes.

Sem fórmula pronta — pense:

quem são:
- clientes top?
- clientes médios?
- clientes fracos?

💡 Dica:

Você pode usar:

quantis (top 20%, etc)

🧭 ETAPA 5 — Análise

Agora você responde perguntas reais:

Top clientes representam quanto da receita?
Existe concentração?
Muitos clientes geram pouco valor?
🧭 ETAPA 6 — Visualização (agora com propósito)

Aqui muda o jogo:

Você vai escolher gráficos para responder perguntas.

Exemplos:

- distribuição de receita por cliente → (histograma)
- top clientes → (bar chart)
- concentração → (curva acumulada)
🧠 ETAPA 7 — INSIGHTS (obrigatório)

Agora você escreve (isso é o que te contrata):

Exemplo do tipo esperado:

- 20% dos clientes geram ~80% da receita
- há grande concentração em poucos clientes
- maioria dos clientes tem baixo ticket médio
⚠️ REGRAS DO PROJETO

Não faça isso:

❌ só código
❌ só gráfico
❌ só tabela

Faça isso:

✔ código claro
✔ nomes bons
✔ métricas úteis
✔ insights escritos
🧠 O QUE ESSE PROJETO DESENVOLVE

Você vai treinar:

✔ pensamento de negócio
✔ análise de clientes (muito usado)
✔ feature engineering
✔ storytelling com dados
🏁 CRITÉRIO DE APROVAÇÃO

1. Clareza do código
2. Qualidade das métricas
3. Nível dos insights
4. Estrutura de análise
🔥 Desafio bônus (se quiser subir nível)

Tente responder:

"se você fosse a empresa, o que faria com essa análise?
'''

In [1]:
!pip install kagglehub

Collecting kagglehub
  Using cached kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Using cached kagglesdk-0.1.16-py3-none-any.whl.metadata (13 kB)
Collecting packaging (from kagglehub)
  Using cached packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pyyaml (from kagglehub)
  Downloading pyyaml-6.0.3-cp311-cp311-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: requests in c:\users\hyego jarllys\appdata\local\programs\python\python311\lib\site-packages (from kagglehub) (2.32.5)
Collecting tqdm (from kagglehub)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting protobuf (from kagglesdk<1.0,>=0.1.14->kagglehub)
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hyego jarllys\appdata\local\programs\python\python311\lib\site-packages (from requests->kagglehub) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hyego jarllys\appdata\local\programs\python\python311\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hyego jarllys\appdata\local\programs\python\python311\lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hyego jarllys\appdata\local\programs\python\python311\lib\site-packages (from requests->kagglehub) (2026.2.25)
Collecting colorama (from tqdm->kagglehub)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Using cached kagglehub-1.0.0-py3-none-any.whl (70 kB)
Using cached kagglesdk-0.1.16-py3-none-any.whl (160 kB)
Using cached packaging-26.0-py3-none-any.whl (74 kB)
Downloading pyyaml-6.0.3-cp311-cp311-win_amd64.whl (158 kB)
   ---------------------------------------- 0.0/158.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/158.8 kB ? eta -:--:--
   ------- ------------------------------- 30.7/158.8 kB 660.6 kB/s eta 0:00:01
   ---------------------------------------- 158.8/158.8 kB 1.6 MB/s eta 0:00:00
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
   ---------------------------------------- 0.0/437.9 kB ? eta -:--:--
   ------------------------- -------------- 276.5/437.9 kB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 437.9/437.9 kB 6.8 MB/s eta 0:00:00
Installing collected packages: pyyaml, protobuf, packaging, colorama, tqdm, kagglesdk, kagglehub
Successfully installed colorama-0.4.6 kagglehub-1.0.0 kagglesdk-0.1.16 packaging-26.0 protobuf-7.34.1 pyyaml-6.0.3 tqdm-4.67.3

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\Hyego Jarllys\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vivek468/superstore-dataset-final")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Hyego Jarllys\.cache\kagglehub\datasets\vivek468\superstore-dataset-final\versions\1

In [ ]:
import os

# Listar arquivos no diretório do dataset
arquivo=os.listdir(path)
print(arquivo)

['Sample - Superstore.csv']

In [8]:
import pandas as pd
#ingestão do dataset
data= r'C:\Users\Hyego Jarllys\.cache\kagglehub\datasets\vivek468\superstore-dataset-final\versions\1\Sample - Superstore.csv'
df=pd.read_csv(data, encoding = 'Windows-1252')
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [10]:
df=df.drop_duplicates()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [12]:
df['Ship Date']=pd.to_datetime(df['Ship Date'])
df['Order Date']=pd.to_datetime(df['Order Date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 3.2 MB

In [13]:
# separar em tabelas diferentes
df_customers = df[['Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region']]
df_orders = df[['Order ID', 'Order Date', 'Ship Date', 'Ship Mode','Customer ID', 'Product ID','Sales', 'Quantity', 'Discount', 'Profit']]
df_products = df[['Product ID', 'Category', 'Sub-Category', 'Product Name']]

In [15]:
df_orders.describe()

,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000
mean,2016-04-30 00:07:12.259355,2016-05-03 23:06:58.571142,229.858001,3.789574,0.156203,28.656896
min,2014-01-03 00:00:00,2014-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2015-05-23 00:00:00,2015-05-27 00:00:00,17.280000,2.000000,0.000000,1.728750
50%,2016-06-26 00:00:00,2016-06-29 00:00:00,54.490000,3.000000,0.200000,8.666500
75%,2017-05-14 00:00:00,2017-05-18 00:00:00,209.940000,5.000000,0.200000,29.364000
max,2017-12-30 00:00:00,2018-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,NaN,NaN,623.245101,2.225110,0.206452,234.260108

In [18]:
import sqlite3

conn= sqlite3.connect('superstore.db')

df_customers.to_sql('customers', conn,  if_exists= 'replace', index= False)
df_orders.to_sql('orders', conn,  if_exists= 'replace', index= False)
df_products.to_sql('products', conn,  if_exists='replace', index= False)

9994